import type { CvData } from './types';

export const cvs: CvData[] = [
  {
    id: '1',
    userId: 'user1',
    title: 'Software Engineer CV',
    personalInfo: {
      name: 'Jane Doe',
      email: 'jane.doe@email.com',
      phone: '+1234567890',
      address: 'San Francisco, CA',
      linkedin: 'linkedin.com/in/janedoe',
      website: 'janedoe.dev',
      avatar: 'https://picsum.photos/seed/avatar1/100/100',
    },
    profile: 'Innovative Software Engineer with 5+ years of experience in developing and scaling web applications. Proficient in React, Node.js, and cloud technologies. Passionate about building great user experiences.',
    experience: [
      {
        id: 'exp1',
        title: 'Senior Frontend Engineer',
        company: 'Tech Solutions Inc.',
        location: 'San Francisco, CA',
        startDate: '2021-01-01',
        endDate: 'Present',
        description: '- Led the development of a new design system.\n- Mentored junior engineers.',
      },
    ],
    education: [
      {
        id: 'edu1',
        institution: 'University of California, Berkeley',
        degree: 'B.S. in Computer Science',
        location: 'Berkeley, CA',
        startDate: '2013-09-01',
        endDate: '2017-05-01',
        description: 'Graduated with honors.',
      },
    ],
    skills: ['React', 'TypeScript', 'Node.js', 'AWS', 'Next.js'],
    languages: ['English (Native)', 'Spanish (Conversational)'],
    projects: [
      {
        id: 'proj1',
        name: 'Personal Portfolio',
        description: 'A personal website to showcase my projects and skills.',
        url: 'janedoe.dev',
      },
    ],
    template: 'modern',
    createdAt: new Date('2023-10-01T10:00:00Z'),
    updatedAt: new Date('2024-05-15T14:30:00Z'),
  },
  {
    id: '2',
    userId: 'user1',
    title: 'Product Manager Resume',
    personalInfo: {
      name: 'Jane Doe',
      email: 'jane.doe@email.com',
      phone: '+1234567890',
      address: 'San Francisco, CA',
      linkedin: 'linkedin.com/in/janedoe',
      website: 'janedoe.dev',
      avatar: 'https://picsum.photos/seed/avatar1/100/100',
    },
    profile: 'Results-driven Product Manager with a track record of launching successful products. Skilled in agile methodologies, user research, and market analysis.',
    experience: [],
    education: [],
    skills: ['Product Strategy', 'Agile', 'JIRA', 'User Research'],
    languages: ['English (Native)'],
    projects: [],
    template: 'professional',
    createdAt: new Date('2024-02-20T09:00:00Z'),
    updatedAt: new Date('2024-04-22T18:00:00Z'),
  },
];
